server:  port: 80
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/testdb
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  devtools: 
    livereload:
      enabled: true        